import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import { useState, useEffect } from "react";

export default function Home({ abi, tokenURI }) {
  const getTokenURI = () => {
    console.log(tokenURI.split(":"));

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={getTokenURI}>get Token URI</button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "https://api.etherscan.io/api?module=contract&action=getabi&address=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d&apikey=4J4V3IRGZBZ73WJ5Q59DUC198F828EFC1F"
  );
  const data = await response.json();
  let abi = data.result;

  const CONTRACT_ADDRESS = '0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d';
  const contract = new ethers.Contract(
    CONTRACT_ADDRESS,
    abi,
    ethers.getDefaultProvider()
  )

  const tokenURI = await contract.tokenURI(2180);
  
  const uriArrToken = tokenURI.split(":");
  const res = await fetch(`https://ipfs.io/${uriArrToken[0]}${uriArrToken[1]}`);
  const metaData = await res.json()
  console.log(console.log(contract));

  return {
    props: {
      abi,
      metaData,
    },
  };
}
